---
title: "Lab 8"
author: "Donya Behroozi"
embed-resources: true
code-fold: true
format: html
toc: true
---
# Load libraries 
```{python}
import pandas as pd
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.metrics import ConfusionMatrixDisplay, make_scorer, accuracy_score
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
```

# Read in data
```{python}
cannabis = pd.read_csv("/Users/donyabehroozi/Downloads/cannabis_full.csv")
cannabis = cannabis.dropna()
cannabis.head()
```

# Part One: Binary Classification

Dataset that only contains indica and sativa types
```{python}
cannabis_filtered = cannabis[(cannabis["Type"]=="indica") | (cannabis["Type"]=="sativa")]
cannabis_filtered.head()
```

**Note**: Since there is no target category identified for this problem, I will be using overall accuracy rate as my model metric for all questions in this section because this metric accounts for the overall proportion of observations that are classified correctly for both the target and non-target classes.

Define X and y:
```{python}
X = cannabis_filtered.drop(['Strain', 'Type', 'Effects', 'Flavor'], axis = 1)
y = cannabis_filtered['Type']
```

```{python}
X.head()
```

```{python}
y.head()
```

## Q1: LDA

Preprocessing:
```{python}
preprocessing = ColumnTransformer(
    [("scale", StandardScaler(), ["Rating"])],
    remainder="passthrough"
).set_output(transform="pandas")

preprocessing.fit_transform(X)
```

LDA:

**Note**: There are no hyperparameters to tune within the LDA function (as far as we have learned), so I will simply tune the preprocessing step to determine the best scaler. 
```{python}
lda_model = Pipeline([
    ("preprocessing", preprocessing),
    ("lda", LinearDiscriminantAnalysis())
])

#define parameter space
param_grid = {
    "preprocessing__scale":[StandardScaler(), MinMaxScaler()] #choice of scaler
}

#perform grid search
grid_search = GridSearchCV(
    lda_model,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best LDA model is the one using a standard scaler for the "Rating" variable due to having the largest cross-validated accuracy (0.86).

Define final best LDA model:
```{python}
lda_final_model = Pipeline([
    ("preprocessing", preprocessing),
    ("lda", LinearDiscriminantAnalysis())
])

lda_model_fitted = lda_final_model.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(lda_model_fitted, X, y)
```

## Q2: QDA

**Note**: There are no hyperparameters to tune within the QDA function (as far as we have learned), so I will simply tune the preprocessing step to determine the best scaler. 
```{python}
#| warning: False
qda_model = Pipeline([
    ("preprocessing", preprocessing),
    ("qda", QuadraticDiscriminantAnalysis())
])

#define parameter space
param_grid = {
    "preprocessing__scale":[StandardScaler(), MinMaxScaler()] #choice of scaler
}

#perform grid search
grid_search = GridSearchCV(
    qda_model,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best QDA model is the one using a min-max scaler for the "Rating" variable due to having the largest cross-validated accuracy (0.439).

Define final best QDA model:
```{python}
#| warning: False
#redefine preprocessing step with min-max scaler
preprocessing_min_max = ColumnTransformer(
    [("scale", MinMaxScaler(), ["Rating"])],
    remainder="passthrough"
    )

qda_final_model = Pipeline([
    ("preprocessing", preprocessing_min_max),
    ("qda", QuadraticDiscriminantAnalysis())
])

qda_model_fitted = qda_final_model.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(qda_model_fitted, X, y)
```

## Q3: SVC

Hyperparameter tuning:
```{python}
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
'svc__C': [0.01, 0.1, 1, 10, 100]}

#perform grid search
svc_model = Pipeline(
  [("preprocessing", preprocessing),
  ("svc", SVC(kernel="linear", probability=True))])

grid_search = GridSearchCV(
    svc_model,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best SVC model is the one using a standard scaler for the "Rating" variable and a regularization strength value (C) of 0.1 due to having the largest cross-validated accuracy (0.869).

Define final best SVC model:
```{python}
#redefine preprocessing step with min-max scaler
svc_final_model = Pipeline([
    ("preprocessing", preprocessing),
    ("svc", SVC(kernel = "linear", probability = True, C = 0.1))])

svc_model_fitted = svc_final_model.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(svc_model_fitted, X, y)
```

## Q4: SVM

Hyperparameter tuning:
```{python}
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
'svm__C': [0.01, 0.1, 1, 10, 100],
'svm__degree': [2,4,6,8,10]}

#perform grid search
svm_model = Pipeline(
  [("preprocessing", preprocessing),
  ("svm", SVC(kernel="poly", probability=True))])

grid_search = GridSearchCV(
    svm_model,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best SVM model is the one using a min-max scaler for the "Rating" variable, a regularization value (C) = 1, and degree = 6 due to having the largest cross-validated accuracy (0.87).

Define final best SVM model:
```{python}
#redefine preprocessing step with min-max scaler
svm_final_model = Pipeline([
    ("preprocessing", preprocessing_min_max),
    ("svm", SVC(kernel = "poly", probability = True, C = 1, degree=6))])

svm_model_fitted = svm_final_model.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(svm_model_fitted, X, y)
```

# Part Two: Natural Multiclass

Full dataset:
```{python}
cannabis.head()
```

Define X and y:
```{python}
X = cannabis.drop(['Strain', 'Type', 'Effects', 'Flavor'], axis = 1)
y = cannabis['Type']
```

```{python}
X.head()
```

```{python}
y.head()
```

## Q1: Decision tree

Tune hyperparameters:
```{python}
dt = DecisionTreeClassifier(random_state = 321)

paramGrid = {
    'ccp_alpha': dt.cost_complexity_pruning_path(X, y).ccp_alphas, 
    'max_depth': range(1, 10+1), 
    'min_samples_leaf': range(1, 10+1)
}

grid_search = GridSearchCV(dt, 
                      paramGrid, 
                      cv = 5, 
                      scoring = 'accuracy', 
                      n_jobs = -1)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best decision tree is the one using a cost complexity value of approximately 0.0031, max depth of 3, and minimum samples per leaf = 1 due to having the largest cross-validated accuracy score (0.625).

Define best tree:
```{python}
dt_final = DecisionTreeClassifier(ccp_alpha = 0.0030597287744541513, max_depth = 3, min_samples_leaf = 1, random_state = 321)

dt_final_fitted = dt_final.fit(X, y)
```

Display tree:
```{python}
plt.figure(figsize=(20,10))
tree.plot_tree(dt_final_fitted, feature_names = X.columns, filled = True, rounded = True, fontsize = 10);
```

```{python}
dt_final.classes_
```

"Sleepy" and "energetic" strains are primarily identified as the hybrid type. Strains that are described as "sleepy" and "relaxed" are primarily identified as the sativa type. However, strains that are "sleepy" and not "relaxed" are identified as the hybrid type. Strains that are not "sleepy" but described as having a "citrus" flavor are identified as primarily the indica type. On the other hand, strains that are not described as "sleepy" nor with a "citrus" flavor are primarily identified as a hybrid type but indica comes in a close second.

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(dt_final_fitted, X, y)
```

## Q2: LDA
```{python}
lda_model2 = Pipeline([
    ("preprocessing", preprocessing),
    ("lda", LinearDiscriminantAnalysis())
])

#define parameter space
param_grid = {
    "preprocessing__scale":[StandardScaler(), MinMaxScaler()] #choice of scaler
}

#perform grid search
grid_search = GridSearchCV(
    lda_model2,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best LDA model is the one using a standard scaler for the "Rating" variable due to having the largest cross-validated accuracy (0.628).

Define final best LDA model:
```{python}
lda_final_model2 = Pipeline([
    ("preprocessing", preprocessing),
    ("lda", LinearDiscriminantAnalysis())
])

lda_model2_fitted = lda_final_model2.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(lda_model2_fitted, X, y)
```

## Q2: QDA
```{python}
#| warning: False
qda_model2 = Pipeline([
    ("preprocessing", preprocessing),
    ("qda", QuadraticDiscriminantAnalysis())
])

#define parameter space
param_grid = {
    "preprocessing__scale":[StandardScaler(), MinMaxScaler()] #choice of scaler
}

#perform grid search
grid_search = GridSearchCV(
    qda_model2,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best QDA model is the one using a min-max scaler for the "Rating" variable due to having the largest cross-validated accuracy (0.236).

Define final best QDA model:
```{python}
#| warning: False
#redefine preprocessing step with min-max scaler
preprocessing_min_max = ColumnTransformer(
    [("scale", MinMaxScaler(), ["Rating"])],
    remainder="passthrough"
    )

qda_final_model2 = Pipeline([
    ("preprocessing", preprocessing_min_max),
    ("qda", QuadraticDiscriminantAnalysis())
])

qda_model2_fitted = qda_final_model2.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(qda_model2_fitted, X, y)
```

## Q2: KNN
```{python}
#define pipeline
KNN_model = Pipeline([
    ("preprocessing", preprocessing),
    ("knn", KNeighborsClassifier())
])

#define parameter space
param_grid = {
    "preprocessing__scale":[StandardScaler(), MinMaxScaler()], #choice of scaler
    "knn__n_neighbors": list(range(1,20+1)), #choice of k
    "knn__p": [1,2], #choice of distance (1 = Manhattan, 2 = Euclidean)
}

#perform grid search
grid_search = GridSearchCV(
    KNN_model,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best KNN model is the one using a standard scaler for the "Rating" variable, k = 17 neighbors, and Euclidean distance due to having the largest cross-validated accuracy (0.611).

Define best KNN model:
```{python}
KNN_model_final = Pipeline([
    ("preprocessing", preprocessing),
    ("knn", KNeighborsClassifier(n_neighbors=17, p = 2))
])

KNN_model_fitted = KNN_model_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(KNN_model_fitted, X, y)
```

## Q3

My metrics were worse than in part one across all of my models. This makes sense as the models are not predicting a binary target variable anymore, they are predicting for a multiclass target variable. Therefore, the multiclass classification models are more prone to errors than the binary classification models as there is more than one class of the target variable that the model can incorrectly identify. According to the confusion matrices in this section, it appears that each model made the most errors distinguishing between hybrid and indica or sativa types. This is expected though, as hybrid strains of cannabis are created by crossbreeding indica and sativa plants, so they are essentially a blend of both plant's effects. Therefore, it makes sense that the models are misclassifying hybrid types as indica or sativa types and vice versa as hybrid types are created from indica/sativa strains.

# Part Three: Multiclass from Binary

## Q1: Indica vs. Not Indica

Create new column in dataset for indica dummy variable:
```{python}
cannabis["indica"] = (cannabis["Type"]=="indica")*1
cannabis.head()
```

Define X and y:
```{python}
X = cannabis.drop(['Strain', 'Type', 'Effects', 'Flavor', 'indica'], axis = 1)
y = cannabis['indica']
```

```{python}
X.head()
```

```{python}
y.head()
```

**SVC**
```{python}
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
'svc__C': [0.01, 0.1, 1, 10, 100]}

#perform grid search
svc_model_ovr = Pipeline(
  [("preprocessing", preprocessing),
  ("svc", SVC(kernel="linear", probability=True))])

grid_search = GridSearchCV(
    svc_model_ovr,
    param_grid=param_grid,
    scoring="f1",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best F1 score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best SVC model for this OvR approach is the one using a standard scaler for the "Rating" variable and a regularization strength value (C) of 0.1 due to having the largest F1 score (0.662).

Define best SVC model:
```{python}
svc_ovr_final = Pipeline(
  [("preprocessing", preprocessing),
  ("svc", SVC(kernel="linear", probability=True, C = 0.1))])

svc_ovr_fitted = svc_ovr_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(svc_ovr_final, X, y)
```

**Logistic Regression**

To choose the best logistic regression model, I will determine which penalty (Ridge, Lasso, Elastic Net), regularization strength (C), and type of scaling (standard, min-max) will result in the largest F1 score.

```{python}
#| warning: False
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
"logit__penalty":["l1", "l2", "elasticnet"],
"logit__C":[0.001, 0.01, 0.1, 1, 10],
"logit__l1_ratio": [0.0, 0.25, 0.5, 0.75, 1.0]}

#perform grid search
logit_model = Pipeline(
  [("preprocessing", preprocessing),
  ("logit", LogisticRegression(solver = "saga", max_iter = 5000, random_state=321))])

grid_search = GridSearchCV(
    logit_model,
    param_grid=param_grid,
    scoring="f1",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best F1 score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best logistic regression model for this OvR approach is the one using a min-max scaler for the "Rating" variable, an elastic net penalty with l1 ratio = 0.75, and regularization strength value (C) of 0.1 due to having the largest F1 score (0.659).

Define best logistic regression model:
```{python}
logit_model_final = Pipeline(
  [("preprocessing", preprocessing_min_max),
  ("logit", LogisticRegression(C = 0.1, l1_ratio=0.75, penalty="elasticnet", solver = "saga", random_state=321))])

logit_final_fitted = logit_model_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(logit_final_fitted, X, y)
```

## Q1: Sativa vs. Not Sativa

Create new column in dataset for sativa dummy variable:
```{python}
cannabis["sativa"] = (cannabis["Type"]=="sativa")*1
cannabis.head()
```

Define X and y:
```{python}
X = cannabis.drop(['Strain', 'Type', 'Effects', 'Flavor', 'indica', 'sativa'], axis = 1)
y = cannabis['sativa']
```

```{python}
X.head()
```

```{python}
y.head()
```

**SVC**
```{python}
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
'svc__C': [0.01, 0.1, 1, 10, 100]}

#perform grid search
svc_model_ovr2 = Pipeline(
  [("preprocessing", preprocessing),
  ("svc", SVC(kernel="linear", probability=True))])

grid_search = GridSearchCV(
    svc_model_ovr2,
    param_grid=param_grid,
    scoring="f1",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best F1 score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best SVC model for this OvR approach is the one using a min-max scaler for the "Rating" variable and a regularization strength value (C) of 100 due to having the largest F1 score (0.296).

Define best SVC model:
```{python}
svc_ovr2_final = Pipeline(
  [("preprocessing", preprocessing_min_max),
  ("svc", SVC(kernel="linear", probability=True, C = 100))])

svc_ovr2_fitted = svc_ovr2_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(svc_ovr2_final, X, y)
```

**Logistic Regression**
```{python}
#| warning: False
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
"logit__penalty":["l1", "l2", "elasticnet"],
"logit__C":[0.001, 0.01, 0.1, 1, 10],
"logit__l1_ratio": [0.0, 0.25, 0.5, 0.75, 1.0]}

#perform grid search
logit_model2 = Pipeline(
  [("preprocessing", preprocessing),
  ("logit", LogisticRegression(solver = "saga", max_iter = 5000, random_state=321))])

grid_search = GridSearchCV(
    logit_model2,
    param_grid=param_grid,
    scoring="f1",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best F1 score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best logistic regression model for this OvR approach is the one using a standard scaler for the "Rating" variable, a ridge penalty with a regularization strength value (C) of 10 due to having the largest F1 score (0.405).

Define best logistic regression model:
```{python}
logit_model2_final = Pipeline(
  [("preprocessing", preprocessing),
  ("logit", LogisticRegression(C = 10, penalty="l2", solver = "saga", random_state=321, max_iter=5000))])

logit_final2_fitted = logit_model2_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(logit_final2_fitted, X, y)
```

## Q1: Hybrid vs. Not Hybrid

Create new column in dataset for hybrid dummy variable:
```{python}
cannabis["hybrid"] = (cannabis["Type"]=="hybrid")*1
cannabis.head()
```

Define X and y:
```{python}
X = cannabis.drop(['Strain', 'Type', 'Effects', 'Flavor', 'indica', 'sativa', 'hybrid'], axis = 1)
y = cannabis['hybrid']
```

```{python}
X.head()
```

```{python}
y.head()
```

**SVC**
```{python}
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
'svc__C': [0.01, 0.1, 1, 10, 100]}

#perform grid search
svc_model_ovr3 = Pipeline(
  [("preprocessing", preprocessing),
  ("svc", SVC(kernel="linear", probability=True))])

grid_search = GridSearchCV(
    svc_model_ovr3,
    param_grid=param_grid,
    scoring="f1",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best F1 score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best SVC model for this OvR approach is the one using a standard scaler for the "Rating" variable and a regularization strength value (C) of 0.1 due to having the largest F1 score (0.684).

Define best SVC model:
```{python}
svc_ovr3_final = Pipeline(
  [("preprocessing", preprocessing),
  ("svc", SVC(kernel="linear", probability=True, C = 0.1))])

svc_ovr3_fitted = svc_ovr3_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(svc_ovr3_final, X, y)
```

**Logistic Regression**
```{python}
#| warning: False
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
"logit__penalty":["l1", "l2", "elasticnet"],
"logit__C":[0.001, 0.01, 0.1, 1, 10],
"logit__l1_ratio": [0.0, 0.25, 0.5, 0.75, 1.0]}

#perform grid search
logit_model3 = Pipeline(
  [("preprocessing", preprocessing),
  ("logit", LogisticRegression(solver = "saga", max_iter = 5000, random_state=321))])

grid_search = GridSearchCV(
    logit_model3,
    param_grid=param_grid,
    scoring="f1",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best F1 score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best logistic regression model for this OvR approach is the one using a min-max scaler for the "Rating" variable and a ridge penalty with a regularization strength value (C) of 0.001 due to having the largest F1 score (0.691).

Define best logistic regression model:
```{python}
logit_model3_final = Pipeline(
  [("preprocessing", preprocessing_min_max),
  ("logit", LogisticRegression(C = 0.001, penalty="l2", solver = "saga", random_state=321, max_iter=5000))])

logit_final3_fitted = logit_model3_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(logit_final3_fitted, X, y)
```

## Q2

The hybrid vs. not hybrid specification for the logistic regression model performed the best due to having the largest F1 score. The sativa vs. not sativa specification for the SVC model performed the worst due to having the smallest F1 score. It makes intuitive sense that logistic model was best able to identify hybrid types from non-hybrid types because it is more difficult to differentiate indica or sativa types from hybrid types than hybrid types from pure indica or sativa types. Hybrid strains are more easily differentiated from indica/sativa types since hybrid strains are a mix of indica/sativa while indica and sativa are purely single strain types. When we use indica and sativa as the target variables instead, it makes sense that the model has a more difficult time identifying the target class as indica or sativa due to the "rest" component of these models consisting of both pure strains (indica or sativa) and a mix of strains (hybrid). Also, the logistic model generally does a better job with identifying the probability of an observation belonging to a target class, while SVC's goal is to maximize the margin between two classes (better for differentiation). So, it makes sense that the logistic regression model did better than the SVC model in distinguishing the target class from the rest of the classes.

## Q3: Indica vs. Sativa

Reduce dataset to only indica and sativa types:
```{python}
cannabis_ind_sat = cannabis[(cannabis["Type"] == "indica") | (cannabis["Type"] == "sativa")]
```

Define X and y:
```{python}
X = cannabis_ind_sat.drop(['Strain', 'Type', 'Effects', 'Flavor', 'indica', 'sativa', 'hybrid'], axis = 1)
y = cannabis_ind_sat['Type']
```

```{python}
X.head()
```

```{python}
y.head()
```

**SVC**
```{python}
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
'svc__C': [0.01, 0.1, 1, 10, 100]}

#perform grid search
svc_model_ovo = Pipeline(
  [("preprocessing", preprocessing),
  ("svc", SVC(kernel="linear", probability=True))])

grid_search = GridSearchCV(
    svc_model_ovo,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best SVC model for this OvR approach is the one using a standard scaler for the "Rating" variable and a regularization strength value (C) of 0.1 due to having the largest accuracy score (0.869).

Define best SVC model:
```{python}
svc_ovo_final = Pipeline(
  [("preprocessing", preprocessing),
  ("svc", SVC(kernel="linear", probability=True, C = 0.1))])

svc_ovo_fitted = svc_ovo_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(svc_ovo_fitted, X, y)
```

**Logistic Regression**
```{python}
#| warning: False
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
"logit__penalty":["l1", "l2", "elasticnet"],
"logit__C":[0.001, 0.01, 0.1, 1, 10],
"logit__l1_ratio": [0.0, 0.25, 0.5, 0.75, 1.0]}

#perform grid search
logit_model_ovo = Pipeline(
  [("preprocessing", preprocessing),
  ("logit", LogisticRegression(solver = "saga", max_iter = 5000, random_state=321))])

grid_search = GridSearchCV(
    logit_model_ovo,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best logistic regression model for this OvR approach is the one using a standard scaler for the "Rating" variable and a ridge penalty with a regularization strength value (C) of 0.1 due to having the largest accuracy score (0.871).

Define best logistic regression model:
```{python}
logit_ovo_final = Pipeline(
  [("preprocessing", preprocessing),
  ("logit", LogisticRegression(C = 0.1, penalty="l2", solver = "saga", random_state=321, max_iter=5000))])

logit_ovo_fitted = logit_ovo_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(logit_ovo_fitted, X, y)
```

## Q3: Indica vs. Hybrid

Reduce dataset to only indica and hybrid types:
```{python}
cannabis_ind_hyb = cannabis[(cannabis["Type"] == "indica") | (cannabis["Type"] == "hybrid")]
cannabis_ind_hyb.head()
```

Define X and y:
```{python}
X = cannabis_ind_hyb.drop(['Strain', 'Type', 'Effects', 'Flavor', 'indica', 'sativa', 'hybrid'], axis = 1)
y = cannabis_ind_hyb['Type']
```

```{python}
X.head()
```

```{python}
y.head()
```

**SVC**
```{python}
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
'svc__C': [0.01, 0.1, 1, 10, 100]}

#perform grid search
svc_model_ovo2 = Pipeline(
  [("preprocessing", preprocessing),
  ("svc", SVC(kernel="linear", probability=True))])

grid_search = GridSearchCV(
    svc_model_ovo2,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best SVC model for this OvR approach is the one using a standard scaler for the "Rating" variable and a regularization strength value (C) of 10 due to having the largest accuracy score (0.758).

Define best SVC model:
```{python}
svc_ovo2_final = Pipeline(
  [("preprocessing", preprocessing),
  ("svc", SVC(kernel="linear", probability=True, C = 10))])

svc_ovo2_fitted = svc_ovo2_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(svc_ovo2_fitted, X, y)
```

**Logistic Regression**
```{python}
#| warning: False
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
"logit__penalty":["l1", "l2", "elasticnet"],
"logit__C":[0.001, 0.01, 0.1, 1, 10],
"logit__l1_ratio": [0.0, 0.25, 0.5, 0.75, 1.0]}

#perform grid search
logit_model_ovo2 = Pipeline(
  [("preprocessing", preprocessing),
  ("logit", LogisticRegression(solver = "saga", max_iter = 5000, random_state=321))])

grid_search = GridSearchCV(
    logit_model_ovo2,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best logistic regression model for this OvR approach is the one using a min-max scaler for the "Rating" variable and a ridge penalty with a regularization strength value (C) of 0.1 due to having the largest accuracy score (0.763).

Define best logistic regression model:
```{python}
logit_ovo2_final = Pipeline(
  [("preprocessing", preprocessing_min_max),
  ("logit", LogisticRegression(C = 0.1, penalty="l2", solver = "saga", random_state=321, max_iter=5000))])

logit_ovo2_fitted = logit_ovo2_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(logit_ovo2_fitted, X, y)
```

## Q3: Hybrid vs. Sativa

Reduce dataset to only sativa and hybrid types:
```{python}
cannabis_sat_hyb = cannabis[(cannabis["Type"] == "sativa") | (cannabis["Type"] == "hybrid")]
cannabis_sat_hyb.head()
```

Define X and y:
```{python}
X = cannabis_sat_hyb.drop(['Strain', 'Type', 'Effects', 'Flavor', 'indica', 'sativa', 'hybrid'], axis = 1)
y = cannabis_sat_hyb['Type']
```

```{python}
X.head()
```

```{python}
y.head()
```

**SVC**
```{python}
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
'svc__C': [0.01, 0.1, 1, 10, 100]}

#perform grid search
svc_model_ovo3 = Pipeline(
  [("preprocessing", preprocessing),
  ("svc", SVC(kernel="linear", probability=True))])

grid_search = GridSearchCV(
    svc_model_ovo3,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best SVC model for this OvR approach is the one using a min-max scaler for the "Rating" variable and a regularization strength value (C) of 1 due to having the largest accuracy score (0.747).

Define best SVC model:
```{python}
svc_ovo3_final = Pipeline(
  [("preprocessing", preprocessing_min_max),
  ("svc", SVC(kernel="linear", probability=True, C = 1))])

svc_ovo3_fitted = svc_ovo3_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(svc_ovo3_fitted, X, y)
```

**Logistic Regression**
```{python}
#| warning: False
#define parameter space
param_grid = {"preprocessing__scale":[StandardScaler(), MinMaxScaler()],
"logit__penalty":["l1", "l2", "elasticnet"],
"logit__C":[0.001, 0.01, 0.1, 1, 10],
"logit__l1_ratio": [0.0, 0.25, 0.5, 0.75, 1.0]}

#perform grid search
logit_model_ovo3 = Pipeline(
  [("preprocessing", preprocessing),
  ("logit", LogisticRegression(solver = "saga", max_iter = 5000, random_state=321))])

grid_search = GridSearchCV(
    logit_model_ovo3,
    param_grid=param_grid,
    scoring="accuracy",
    cv=5,
    n_jobs = -1
)

grid_search.fit(X, y)
print("Best accuracy score:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)
```

The best logistic regression model for this OvR approach is the one using a min-max scaler for the "Rating" variable and a lasso penalty with a regularization strength value (C) of 0.1 due to having the largest accuracy score (0.754).

Define best logistic regression model:
```{python}
logit_ovo3_final = Pipeline(
  [("preprocessing", preprocessing_min_max),
  ("logit", LogisticRegression(C = 0.1, penalty="l1", solver = "saga", random_state=321, max_iter=5000))])

logit_ovo3_fitted = logit_ovo3_final.fit(X, y)
```

Confusion matrix:
```{python}
ConfusionMatrixDisplay.from_estimator(logit_ovo3_fitted, X, y)
```

## Q4

The indica vs. sativa specification for the logistic regression model performed the best due to having the largest accuracy score. The hybrid vs. sativa specification for the SVC model performed the worst due to having the smallest accuracy score. It makes intuitive sense that logistic model was better able to identify indica types from sativa types than indica/sativa types from the hybrid type because indica and sativa are distinct strains while hybrid types are cross-bred indica and sativa strains, therefore making it more difficult to differentiate between a strain that is purely indica/sativa and a strain that contains a percentage of indica/sativa in it. Additionally, the sativa vs. not sativa OvR model performed the worst in terms of F1 score in the previous section, so it makes sense that the hybrid vs. sativa OvO model also performed the worst in this section. Although the SVC model did not perform the best, it is noteworthy that this model performed much better for the OvO specifications in this section than the OvR specifications in the previous section. This is likely due to the fact that SVC's goal is to maximize the margin between two classes, so is therefore better at differentiating between classes rather than accurately identifying values of the target variable for each observation.

## Q5

Logistic Regression: According to the documentation of the `LogisticRegression()` function it appears that the logistic regression function would automatically take an OvR approach, as the default method of the `multi_class` argument automatically select `ovr` as the classification method.

SVC: According to the documentation of the `SVC()` function, the default method to train the SVC model is `ovo`. Therefore, the SVC model would automatically take an OvO approach.