---
title: "Lab 6"
author: "Donya Behroozi"
embed-resources: true
code-fold: true
format: html
toc: true
---

# Load libraries and read in data
```{python}
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_selector, ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV
from plotnine import *

baseball = pd.read_csv("/Users/donyabehroozi/Downloads/Hitters.csv")
baseball.head()
```


# Clean data

First, let's check our variable types:
```{python}
baseball.dtypes
```

The variable types appear to be as expected given the data description.

Now, check for missing variables:
```{python}
baseball.isna().sum()
```

There are 59 missing salaries. I will drop these values from the data frame. But we should not that this is a concern with this data set since our response variable contains 18% missing values.
```{python}
baseball = baseball.dropna()
baseball.shape[0]
```

Our data frame now has 322 - 59 = 263 observations.

# Part I: Different Model Specs

## A. Regression without regularization

1. Create a pipeline that includes all the columns as predictors for Salary, and performs ordinary linear regression.

First let's define our X and y variables:
```{python}
X = baseball.drop(["Salary"], axis = 1)
y = baseball["Salary"]
```

```{python}
X.head()
```

```{python}
y.head()
```

**Linear regression pipeline**

Column transformer:
```{python}
#column transformer that dummifies categorical variables, passes remainder through
ct_dummify_stdz = ColumnTransformer(
  [
    ("dummify",
    OneHotEncoder(sparse_output = False, handle_unknown='ignore', drop = "first"),
    make_column_selector(dtype_include=object)),
    ("standardize",
    StandardScaler(),
    make_column_selector(dtype_include=np.number))
  ],
  remainder = "passthrough"
).set_output(transform="pandas")

ct_dummify_stdz.fit_transform(X).head()
```

Full pipeline:
```{python}
lr_pipeline = Pipeline(
  [("preprocessing", ct_dummify_stdz),
  ("linear_regression", LinearRegression())]
)

lr_pipeline
```

2. Fit this pipeline to the full dataset, and interpret a few of the most important coefficients.
```{python}
lr_pipeline_fitted = lr_pipeline.fit(X, y)
lr_coefs = lr_pipeline_fitted.named_steps['linear_regression'].coef_
lr_abs_coefs = np.abs(lr_coefs)
lr_coef_names = lr_pipeline_fitted.named_steps["preprocessing"].get_feature_names_out()
lr_coef_df = pd.DataFrame({"Variable": lr_coef_names, "Coef": lr_coefs, "Abs Coef": lr_abs_coefs}).sort_values("Abs Coef", ascending=False)
lr_coef_df.head(5)
```

**Interpretations**

- CRuns: Salary is expected to increase by 480,747.1 dollars for each one standard deviation increase in number of runs during a player's career, holding other predictors constant.

- CAtBat: Salary is expected to decrease by 391,038.7 dollars for each one standard deviation increase in number of times at bat during a player's career, holding other predictors constant.

- Hits: Salary is expected to increase by 337,830.5 dollars for each one standard deviation increase in number of hits in 1986, holding other predictors constant.

- AtBat: Salary is expected to decrease by 291,094.6 dollars for each one standard deviation increase in number of times at bat in 1986, holding other predictors constant.

- CRBI: Salary is expected to increase by 260,689.9 dollars for each one standard deviation increase in number of runs batted in a player's career, holding other predictors constant.

3. Use cross-validation to estimate the MSE you would expect if you used this pipeline to predict 1989 salaries.
```{python}
lr_scores = cross_val_score(lr_pipeline, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

lr_mse = lr_scores.mean()*-1
lr_mse
```

The MSE we would expect if we used this pipeline to predict 1989 salaries is 121,136.31 dollars squared.

## B. Ridge regression

1. Create a pipeline that includes all the columns as predictors for Salary, and performs ordinary ridge regression.
```{python}
ridge_pipeline = Pipeline(
  [("preprocessing", ct_dummify_stdz),
  ("ridge_regression", Ridge())]
)

ridge_pipeline
```

2. Use cross-validation to tune the lambda hyperparameter.
```{python}
alphas = {'ridge_regression__alpha': np.array([100, 10, 1, 0.1, 0.01])}
gscv = GridSearchCV(ridge_pipeline, param_grid=alphas, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_ridge_regression__alpha', 'mean_test_score']]
```

It appears that the model that performs the best out of all the given lambda values is the model with lambda = 100.

3. Fit the pipeline with your chosen lambda to the full dataset, and interpret a few of the most important coefficients.
```{python}
ridge_pipeline_final = Pipeline(
  [("preprocessing", ct_dummify_stdz),
  ("ridge_regression", Ridge(alpha = 100))]
)

ridge_pipeline_fitted = ridge_pipeline_final.fit(X, y)
ridge_coefs = ridge_pipeline_fitted.named_steps['ridge_regression'].coef_
ridge_abs_coefs = np.abs(ridge_coefs)
ridge_coef_names = ridge_pipeline_fitted.named_steps["preprocessing"].get_feature_names_out()
ridge_coef_df = pd.DataFrame({"Variable": ridge_coef_names, "Coef": ridge_coefs, "Abs Coef": ridge_abs_coefs})
ridge_coef_df = ridge_coef_df.sort_values("Abs Coef", ascending=False)
ridge_coef_df.head(5)
```

**Interpretations**

- PutOuts: Salary is expected to increase by 57,152 dollars for each one standard deviation increase in number of put outs in 1986, holding other predictors constant.

- Division_W:
```{python}
baseball['Division'].value_counts()
```

SD(Division_W) = sqrt((134/263)*(1-(134/263))) = 0.5

-53.025*0.5 = -26.5125

Salary is is expected to be 26,513 dollars less for players that were in division W at the end of 1986 than division E, holding other predictors constant.

- Hits: Salary is expected to increase by 49,783.3 dollars for each one standard deviation increase in number of hits in 1986, holding other predictors constant.

- CRBI: Salary is expected to increase by 46,964.1 dollars for each one standard deviation increase in number of runs batted in during a player's career, holding other predictors constant.

- CRuns: Salary is expected to increase by 45,812.2 dollars for each one standard deviation increase in number of runs during a player's career, holding other predictors constant.

4. Report the MSE you would expect if you used this pipeline to predict 1989 salaries.

```{python}
ridge_scores = cross_val_score(ridge_pipeline_final, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

ridge_mse = ridge_scores.mean()*-1
ridge_mse
```

The MSE we would expect if we used this pipeline to predict 1989 salaries is 121,274.424 dollars squared.

## C. Lasso Regression

1. Create a pipeline that includes all the columns as predictors for Salary, and performs ordinary lasso regression.
```{python}
lasso_pipeline = Pipeline(
  [("preprocessing", ct_dummify_stdz),
  ("lasso_regression", Lasso())]
)

lasso_pipeline
```

2. Use cross-validation to tune the lambda hyperparameter.
```{python}
#| warning: false
alphas = {'lasso_regression__alpha': np.array([100, 10, 1, 0.1, 0.01])}
gscv = GridSearchCV(lasso_pipeline, param_grid=alphas, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_lasso_regression__alpha', 'mean_test_score']].sort_values("mean_test_score", ascending = False)
```

It appears that the model that performs the best out of all the given lambda values is the model with lambda = 10.

3. Fit the pipeline with your chosen lambda to the full dataset, and interpret a few of the most important coefficients.
```{python}
lasso_pipeline_final = Pipeline(
  [("preprocessing", ct_dummify_stdz),
  ("lasso_regression", Lasso(alpha = 10))]
)

lasso_pipeline_fitted = lasso_pipeline_final.fit(X, y)
lasso_coefs = lasso_pipeline_fitted.named_steps['lasso_regression'].coef_
lasso_abs_coefs = np.abs(lasso_coefs)
lasso_coef_names = lasso_pipeline_fitted.named_steps["preprocessing"].get_feature_names_out()
lasso_coef_df = pd.DataFrame({"Variable": lasso_coef_names, "Coef": lasso_coefs, "Abs Coef": lasso_abs_coefs})
lasso_coef_df = lasso_coef_df.sort_values("Abs Coef", ascending=False)
lasso_coef_df.head(5)
```

**Interpretations** 

- CRBI: Salary is expected to increase by 134,032 dollars for each one standard deviation increase in number of runs batted in during a player's career, holding other predictors constant.

- Division_W: 

-95.413203*0.5 = -47.7065

Salary is is expected to be 47,706.5 dollars less for players that were in division W at the end of 1986 than division E, holding other predictors constant.

- Hits: Salary is expected to increase by 88,741.6 dollars for each one standard deviation increase in number of hits in 1986, holding other predictors constant.

- CRuns: Salary is expected to increase by 72,227.5 dollars for each one standard deviation increase in number of runs during a player's career, holding other predictors constant.

- PutOuts: Salary is expected to increase by 66,737 dollars for each one standard deviation increase in number of put outs in 1986, holding other predictors constant.

4. Report the MSE you would expect if you used this pipeline to predict 1989 salaries.
```{python}
lasso_scores = cross_val_score(lasso_pipeline_final, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

lasso_mse = lasso_scores.mean()*-1
lasso_mse
```

The MSE we would expect if we used this pipeline to predict 1989 salaries is 121,828.141 dollars squared.

## D. Elastic Net

1. Create a pipeline that includes all the columns as predictors for Salary, and performs ordinary elastic net regression.
```{python}
elastic_net_pipeline = Pipeline(
  [("preprocessing", ct_dummify_stdz),
  ("elastic_net_regression", ElasticNet())]
)

elastic_net_pipeline
```

2. Use cross-validation to tune the lambda and alpha hyperparameters.
```{python}
#| warning: false
param_grid = {
    "elastic_net_regression__alpha": np.array([100, 10, 1, 0.1, 0.01]),
    "elastic_net_regression__l1_ratio": np.array([0.0, 0.25, 0.5, 0.75, 1.0]),
}

gscv = GridSearchCV(elastic_net_pipeline, param_grid=param_grid, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_elastic_net_regression__alpha', 'param_elastic_net_regression__l1_ratio', 'mean_test_score']].sort_values("mean_test_score", ascending = False).head(5)
```

It appears that the model that performs the best out of all the given lambda and alpha values is the model with lambda = 1 and alpha = 0.25

3. Fit the pipeline with your chosen hyperparameters to the full dataset, and interpret a few of the most important coefficients.
```{python}
elastic_net_pipeline_final = Pipeline(
  [("preprocessing", ct_dummify_stdz),
  ("elastic_net_regression", ElasticNet(alpha = 1, l1_ratio=0.25))]
)

elastic_net_pipeline_fitted = elastic_net_pipeline_final.fit(X, y)
elastic_coefs = elastic_net_pipeline_fitted.named_steps['elastic_net_regression'].coef_
elastic_abs_coefs = np.abs(elastic_coefs)
elastic_coef_names = elastic_net_pipeline_fitted.named_steps["preprocessing"].get_feature_names_out()
elastic_coef_df = pd.DataFrame({"Variable": elastic_coef_names, "Coef": elastic_coefs, "Abs Coef": elastic_abs_coefs})
elastic_coef_df = elastic_coef_df.sort_values("Abs Coef", ascending=False)
elastic_coef_df.head(5)
```

**Interpretations** 

- PutOuts: Salary is expected to increase by 46,140.7 dollars for each one standard deviation increase in number of put outs in 1986, holding other predictors constant.

- CRBI: Salary is expected to increase by 38,483.1 dollars for each one standard deviation increase in number of runs batted in during a player's career, holding other predictors constant.

- Hits: Salary is expected to increase by 38,419.5 dollars for each one standard deviation increase in number of hits in 1986, holding other predictors constant.

- CRuns: Salary is expected to increase by 37,725.7 dollars for each one standard deviation increase in number of runs during a player's career, holding other predictors constant.

- CHits: Salary is expected to increase by 36,749 dollars for each one standard deviation increase in number of hits during a player's career, holding other predictors constant.

4. Report the MSE you would expect if you used this pipeline to predict 1989 salaries.
```{python}
elastic_scores = cross_val_score(elastic_net_pipeline_final, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

elastic_mse = elastic_scores.mean()*-1
elastic_mse
```

The MSE we would expect if we used this pipeline to predict 1989 salaries is 122,065.013 dollars squared.

# Part II. Variable Selection

## Linear Regression model

1. Using only the one best numeric variable.

It appears that the most impactful/important numeric variable in the linear regression model is CRuns.
```{python}
#column transformer that only standardizes CRuns
ct_lrft1 = ColumnTransformer(
  [
    ("standardize",
    StandardScaler(),
    ["CRuns"])
  ],
  remainder = "drop"
).set_output(transform="pandas")

lr_ft1_pipeline = Pipeline(
  [("preprocessing", ct_lrft1),
  ("linear_regression", LinearRegression())]
)

lr_ft1_scores = cross_val_score(lr_ft1_pipeline, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

lr_ft1_mse = lr_ft1_scores.mean()*-1
lr_ft1_mse
```

The MSE of this feature set is 143,812.936 dollars squared.

2. Using only the five best variables.

The five most impactful/important numeric variables appear to be CRuns, CAtBat, Hits, AtBat, CRBI.
```{python}
#column transformer that dummifies categorical variables, passes remainder through
ct_lrft2 = ColumnTransformer(
  [
    ("standardize",
    StandardScaler(),
    ["CRuns", "CAtBat", "Hits", "AtBat", "CRBI"])
  ],
  remainder = "drop"
).set_output(transform="pandas")


lr_ft2_pipeline = Pipeline(
  [("preprocessing", ct_lrft2),
  ("linear_regression", LinearRegression())]
)

lr_ft2_scores = cross_val_score(lr_ft2_pipeline, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

lr_ft2_mse = lr_ft2_scores.mean()*-1
lr_ft2_mse
```

The MSE of this feature set is 121,228.218 dollars squared.

3. Using the five best numeric variables and their interactions with the one best categorical variable.

```{python}
mask = lr_coef_df.sort_values("Abs Coef", ascending=False)["Variable"].str.contains("dummify")
lr_coef_df[mask]
```

The five best numeric variables (as found above) are CRuns, CAtBat, Hits, AtBat, CRBI. The best categorical variable appears to be Division_W.

Let's first define our column transformers.

Column transformer that dummifies and standardizes variables of interest:
```{python}
ct_lrft3_dummify_stdz = ColumnTransformer(
  [
    ("dummify",
    OneHotEncoder(sparse_output = False, handle_unknown='ignore', drop = "first"),
    ["Division"]),
    ("standardize",
    StandardScaler(),
    ["CRuns", "CAtBat", "Hits", "AtBat", "CRBI"])
  ],
  remainder = "drop"
).set_output(transform="pandas")

X_dummified = ct_lrft3_dummify_stdz.fit_transform(X)
X_dummified.head()
```

Column transformer that makes interactions between numeric and categorical variables:
```{python}
ct_lrft3_inter = ColumnTransformer(
  [
    ("interactionCRuns", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__CRuns"]),
    ("interactionCAtBat", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__CAtBat"]),
    ("interactionHits", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__Hits"]),
    ("interactionAtBat", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__AtBat"]),
    ("interactionCRBI", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__CRBI"])
  ],
  remainder = "drop"
).set_output(transform = "pandas")

ct_lrft3_inter.fit_transform(X_dummified).head()
```

Create pipeline and find MSE:
```{python}
lr_ft3_pipeline = Pipeline(
  [("dummify_stdz", ct_lrft3_dummify_stdz),
  ("interactions", ct_lrft3_inter),
  ("linear_regression", LinearRegression())]
)

lr_ft3_scores = cross_val_score(lr_ft3_pipeline, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

lr_ft3_mse = lr_ft3_scores.mean()*-1
lr_ft3_mse
```

The MSE of this feature set is 127,199.713 dollars squared.

The combination of features that performed the best for the linear regression model is the model using only the five best numeric variables: CRuns, CAtBat, Hits, AtBat, CRBI (smallest MSE = 121,228.218).

## Ridge regression model

1. Using only the one best numeric variable.

It appears that the most impactful/important numeric variable in the ridge regression model is PutOuts.
```{python}
#column transformer that only standardizes PutOuts
ct_ridgeft1 = ColumnTransformer(
  [
    ("standardize",
    StandardScaler(),
    ["PutOuts"])
  ],
  remainder = "drop"
).set_output(transform="pandas")

#fit pipeline
ridgeft1_pipeline = Pipeline(
  [("preprocessing", ct_ridgeft1),
  ("ridge_regression", Ridge())]
)

#tune lambda
alphas = {'ridge_regression__alpha': np.array([100, 10, 1, 0.1, 0.01])}
gscv = GridSearchCV(ridgeft1_pipeline, param_grid=alphas, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_ridge_regression__alpha', 'mean_test_score']]
```

The model that performs the best out of the given lambdas is the model with lambda = 100.

```{python}
ridgeft1_pipeline_final = Pipeline(
  [("preprocessing", ct_ridgeft1),
  ("ridge_regression", Ridge(alpha = 100))]
)

ridgeft1_scores = cross_val_score(ridgeft1_pipeline_final, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

ridgeft1_mse = ridgeft1_scores.mean()*-1
ridgeft1_mse
```

The MSE of this feature set is 193,417.809 dollars squared.

2. Using only the five best variables.

```{python}
ridge_coef_df.head(6)
```

It appears that five the most impactful/important numeric variables in the ridge regression model are PutOuts, Hits, CRBI, CRuns, and CHits. 
```{python}
#column transformer that only standardizes PutOuts, Hits, CRBI, CRuns, and CHits
ct_ridgeft2 = ColumnTransformer(
  [
    ("standardize",
    StandardScaler(),
    ["PutOuts", "Hits", "CRBI", "CRuns", "CHits"])
  ],
  remainder = "drop"
).set_output(transform="pandas")

#fit pipeline
ridgeft2_pipeline = Pipeline(
  [("preprocessing", ct_ridgeft2),
  ("ridge_regression", Ridge())]
)

#tune lambda
alphas = {'ridge_regression__alpha': np.array([100, 10, 1, 0.1, 0.01])}
gscv = GridSearchCV(ridgeft2_pipeline, param_grid=alphas, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_ridge_regression__alpha', 'mean_test_score']]
```

The model that performs the best out of the given lambdas is the model with lambda = 100.
```{python}
ridgeft2_pipeline_final = Pipeline(
  [("preprocessing", ct_ridgeft2),
  ("ridge_regression", Ridge(alpha = 100))]
)

ridgeft2_scores = cross_val_score(ridgeft2_pipeline_final, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

ridgeft2_mse = ridgeft2_scores.mean()*-1
ridgeft2_mse
```

The MSE of this feature set is 122,442.744 dollars squared.

3. Using the five best numeric variables and their interactions with the one best categorical variable.

The five best numeric variables (as found above) are PutOuts, Hits, CRBI, CRuns, and CHits. The best categorical variable appears to be Division_W.

Let's first define our column transformers.

Column transformer that dummifies and standardizes variables of interest:
```{python}
ct_ridgeft3_dummify_stdz = ColumnTransformer(
  [
    ("dummify",
    OneHotEncoder(sparse_output = False, handle_unknown='ignore', drop = "first"),
    ["Division"]),
    ("standardize",
    StandardScaler(),
    ["PutOuts", "Hits", "CRBI", "CRuns", "CHits"])
  ],
  remainder = "drop"
).set_output(transform="pandas")

X_dummified = ct_ridgeft3_dummify_stdz.fit_transform(X)
X_dummified.head()
```

Column transformer that makes interactions between numeric and categorical variables:
```{python}
ct_ridgeft3_inter = ColumnTransformer(
  [
    ("interactionPutOuts", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__PutOuts"]),
    ("interactionHits", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__Hits"]),
    ("interactionCRBI", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__CRBI"]),
    ("interactionCRuns", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__CRuns"]),
    ("interactionCHits", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__CHits"])
  ],
  remainder = "drop"
).set_output(transform = "pandas")

ct_ridgeft3_inter.fit_transform(X_dummified).head()
```

Create pipeline:
```{python}
#fit pipeline
ridgeft3_pipeline = Pipeline(
  [("dummify_stdz", ct_ridgeft3_dummify_stdz),
  ("interactions", ct_ridgeft3_inter),
  ("ridge_regression", Ridge())]
)

#tune lambda
alphas = {'ridge_regression__alpha': np.array([100, 10, 1, 0.1, 0.01])}
gscv = GridSearchCV(ridgeft3_pipeline, param_grid=alphas, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_ridge_regression__alpha', 'mean_test_score']]
```

The model that performs the best out of the given lambdas is the model with lambda = 100.
```{python}
ridgeft3_pipeline_final = Pipeline(
  [("dummify_stdz", ct_ridgeft3_dummify_stdz),
  ("interactions", ct_ridgeft3_inter),
  ("ridge_regression", Ridge(alpha = 100))]
)

ridgeft3_scores = cross_val_score(ridgeft3_pipeline_final, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

ridgeft3_mse = ridgeft3_scores.mean()*-1
ridgeft3_mse
```

The MSE of this feature set is 119,058.886 dollars squared.

The combination of features that performed the best for the ridge regression model is the model using the five best numeric variables and their interactions with the one best categorical variable: PutOuts, Hits, CRBI, CRuns, and CHits, Division_W (smallest MSE = 119,058.886).

## Lasso regression model

1. Using only the one best numeric variable.

It appears that the most impactful/important numeric variable is CRBI.
```{python}
#column transformer that only standardizes CRBI
ct_lassoft1 = ColumnTransformer(
  [
    ("standardize",
    StandardScaler(),
    ["CRBI"])
  ],
  remainder = "drop"
).set_output(transform="pandas")

#fit pipeline
lassoft1_pipeline = Pipeline(
  [("preprocessing", ct_lassoft1),
  ("lasso_regression", Lasso())]
)

#tune lambda
alphas = {'lasso_regression__alpha': np.array([100, 10, 1, 0.1, 0.01])}
gscv = GridSearchCV(lassoft1_pipeline, param_grid=alphas, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_lasso_regression__alpha', 'mean_test_score']].sort_values("mean_test_score", ascending = False)
```

The model that performs the best out of the given lambdas is the model with lambda = 10.
```{python}
lassoft1_pipeline_final = Pipeline(
  [("preprocessing", ct_lassoft1),
  ("lasso_regression", Lasso(alpha = 10))]
)

lassoft1_scores = cross_val_score(lassoft1_pipeline_final, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

lassoft1_mse = lassoft1_scores.mean()*-1
lassoft1_mse
```

The MSE of this feature set is 142,236.171 dollars squared.

2. Using the five best numeric variables.
```{python}
lasso_coef_df.head(6)
```

The five best numeric variables are CRBI, Hits, CRuns, PutOuts, and Walks.
```{python}
#column transformer that standardizes CRBI, Hits, CRuns, PutOuts, and Walks
ct_lassoft2 = ColumnTransformer(
  [
    ("standardize",
    StandardScaler(),
    ["CRBI", "Hits", "CRuns", "PutOuts", "Walks"])
  ],
  remainder = "drop"
).set_output(transform="pandas")

#fit pipeline
lassoft2_pipeline = Pipeline(
  [("preprocessing", ct_lassoft2),
  ("lasso_regression", Lasso())]
)

#tune lambda
alphas = {'lasso_regression__alpha': np.array([100, 10, 1, 0.1, 0.01])}
gscv = GridSearchCV(lassoft2_pipeline, param_grid=alphas, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_lasso_regression__alpha', 'mean_test_score']].sort_values("mean_test_score", ascending = False)
```

The model that performs the best out of the given lambdas is the model with lambda = 10.
```{python}
lassoft2_pipeline_final = Pipeline(
  [("preprocessing", ct_lassoft2),
  ("lasso_regression", Lasso(alpha = 10))]
)

lassoft2_scores = cross_val_score(lassoft2_pipeline_final, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

lassoft2_mse = lassoft2_scores.mean()*-1
lassoft2_mse
```

The MSE of this feature set is 121,601.438 dollars squared.

3. Using the five best numeric variables and their interactions with the one best categorical variable.

The five best numeric variables (as found above) are CRBI, Hits, CRuns, PutOuts, and Walks. The best categorical variable appears to be Division_W.

Let’s first define our column transformers.

Column transformer that dummifies and standardizes variables of interest:
```{python}
ct_lassoft3_dummify_stdz = ColumnTransformer(
  [
    ("dummify",
    OneHotEncoder(sparse_output = False, handle_unknown='ignore', drop = "first"),
    ["Division"]),
    ("standardize",
    StandardScaler(),
    ["CRBI", "Hits", "CRuns", "PutOuts", "Walks"])
  ],
  remainder = "drop"
).set_output(transform="pandas")

X_dummified = ct_lassoft3_dummify_stdz.fit_transform(X)
X_dummified.head()
```

Column transformer that makes interactions between numeric and categorical variables:
```{python}
ct_lassoft3_inter = ColumnTransformer(
  [
    ("interactionCRBI", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__CRBI"]),
    ("interactionHits", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__Hits"]),
    ("interactionCRuns", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__CRuns"]),
    ("interactionPutOuts", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__PutOuts"]),
    ("interactionWalk", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__Walks"])
  ],
  remainder = "drop"
).set_output(transform = "pandas")

ct_lassoft3_inter.fit_transform(X_dummified).head()
```

Create pipeline:
```{python}
lassoft3_pipeline = Pipeline(
  [("dummify_stdz", ct_lassoft3_dummify_stdz),
  ("interactions", ct_lassoft3_inter),
  ("lasso_regression", Lasso())]
)

#tune lambda
alphas = {'lasso_regression__alpha': np.array([100, 10, 1, 0.1, 0.01])}
gscv = GridSearchCV(lassoft3_pipeline, param_grid=alphas, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_lasso_regression__alpha', 'mean_test_score']].sort_values('mean_test_score', ascending = False)
```

The model that performs the best out of the given lambdas is the model with lambda = 10.
```{python}
lassoft3_pipeline_final = Pipeline(
  [("dummify_stdz", ct_lassoft3_dummify_stdz),
  ("interactions", ct_lassoft3_inter),
  ("lasso_regression", Lasso(alpha = 10))]
)

lassoft3_scores = cross_val_score(lassoft3_pipeline_final, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

lassoft3_mse = lassoft3_scores.mean()*-1
lassoft3_mse
``` 

The MSE of this feature set is 119,131.849 dollars squared.

The combination of features that performed the best for the lasso regression model is the model using the five best numeric variables and their interactions with the one best categorical variable: CRBI, Hits, CRuns, PutOuts, and Walks, Division_W (smallest MSE = 119,131.849).

## Elastic Net regression model

1. Using only the one best numeric variable.

It appears that the most impactful/important numeric variable is PutOuts.
```{python}
#| warning: false
#column transformer that only standardizes PutOuts
ct_elasticft1 = ColumnTransformer(
  [
    ("standardize",
    StandardScaler(),
    ["PutOuts"])
  ],
  remainder = "drop"
).set_output(transform="pandas")

#fit pipeline
elasticft1_pipeline = Pipeline(
  [("preprocessing", ct_elasticft1),
  ("elastic_net_regression", ElasticNet())]
)

param_grid = {
    "elastic_net_regression__alpha": np.array([100, 10, 1, 0.1, 0.01]),
    "elastic_net_regression__l1_ratio": np.array([0.0, 0.25, 0.5, 0.75, 1.0]),
}

gscv = GridSearchCV(elasticft1_pipeline, param_grid=param_grid, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_elastic_net_regression__alpha', 'param_elastic_net_regression__l1_ratio', 'mean_test_score']].sort_values("mean_test_score", ascending = False).head()
```

The model that performs the best out of all the given lambda and alpha values is the model with lambda = 1 and alpha = 0.25.
```{python}
#| warning: false
elasticft1_pipeline_final = Pipeline(
  [("preprocessing", ct_elasticft1),
  ("elastic_net_regression", ElasticNet(alpha = 1, l1_ratio = 0.25))]
)

elasticft1_scores = cross_val_score(elasticft1_pipeline_final, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

elasticft1_mse = elasticft1_scores.mean()*-1
elasticft1_mse
```

The MSE of this feature set is 194,082.789 dollars squared.

2. Using only the five best numeric variables.

It appears that five the most impactful/important numeric variables in the elastic net regression model are PutOuts, CRBI, Hits, CRuns, and CHits.
```{python}
#| warning: false
#column transformer that standardizes PutOuts, CRBI, Hits, CRuns, and CHits
ct_elasticft2 = ColumnTransformer(
  [
    ("standardize",
    StandardScaler(),
    ["PutOuts", "CRBI", "Hits", "CRuns", "CHits"])
  ],
  remainder = "drop"
).set_output(transform="pandas")

#fit pipeline
elasticft2_pipeline = Pipeline(
  [("preprocessing", ct_elasticft2),
  ("elastic_net_regression", ElasticNet())]
)

param_grid = {
    "elastic_net_regression__alpha": np.array([100, 10, 1, 0.1, 0.01]),
    "elastic_net_regression__l1_ratio": np.array([0.0, 0.25, 0.5, 0.75, 1.0]),
}

gscv = GridSearchCV(elasticft2_pipeline, param_grid=param_grid, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_elastic_net_regression__alpha', 'param_elastic_net_regression__l1_ratio', 'mean_test_score']].sort_values("mean_test_score", ascending = False).head()
```

The model that performs the best out of all the given lambda and alpha values is the model with lambda = 1 and alpha = 0.5.
```{python}
elasticft2_pipeline_final = Pipeline(
  [("preprocessing", ct_elasticft2),
  ("elastic_net_regression", ElasticNet(alpha = 1, l1_ratio = 0.5))]
)

elasticft2_scores = cross_val_score(elasticft2_pipeline_final, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

elasticft2_mse = elasticft2_scores.mean()*-1
elasticft2_mse
```

The MSE of this feature set is 122,611.710 dollars squared.

3. Using the five best numeric variables and their interactions with the one best categorical variable.

```{python}
mask = elastic_coef_df.sort_values("Abs Coef", ascending=False)["Variable"].str.contains("dummify")
elastic_coef_df[mask]
```

The five best numeric variables (as found above) are PutOuts, CRBI, Hits, CRuns, and CHits. The best categorical variable appears to be Division_W.

Let’s first define our column transformers.

Column transformer that dummifies and standardizes variables of interest:
```{python}
ct_elasticft3_dummify_stdz = ColumnTransformer(
  [
    ("dummify",
    OneHotEncoder(sparse_output = False, handle_unknown='ignore', drop = "first"),
    ["Division"]),
    ("standardize",
    StandardScaler(),
    ["PutOuts", "CRBI", "Hits", "CRuns", "CHits"])
  ],
  remainder = "drop"
).set_output(transform="pandas")

X_dummified = ct_elasticft3_dummify_stdz.fit_transform(X)
X_dummified.head()
```

Column transformer that makes interactions between numeric and categorical variables:
```{python}
ct_elasticft3_inter = ColumnTransformer(
  [
    ("interactionPutOuts", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__PutOuts"]),
    ("interactionCRBI", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__CRBI"]),
    ("interactionHits", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__Hits"]),
    ("interactionCRuns", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__CRuns"]),
    ("interactionCHits", PolynomialFeatures(interaction_only = True, include_bias=False), ["dummify__Division_W", "standardize__CHits"])
  ],
  remainder = "drop"
).set_output(transform = "pandas")

ct_elasticft3_inter.fit_transform(X_dummified).head()
```

Create pipeline:
```{python}
#| warning: false
elasticft3_pipeline = Pipeline(
  [("dummify_stdz", ct_elasticft3_dummify_stdz),
  ("interactions", ct_elasticft3_inter),
  ("elastic_net_regression", ElasticNet())]
)

param_grid = {
    "elastic_net_regression__alpha": np.array([100, 10, 1, 0.1, 0.01]),
    "elastic_net_regression__l1_ratio": np.array([0.0, 0.25, 0.5, 0.75, 1.0]),
}

gscv = GridSearchCV(elasticft3_pipeline, param_grid=param_grid, cv = 5, scoring='r2')
gscv_fitted = gscv.fit(X, y)
df_cv_results_ = pd.DataFrame(gscv_fitted.cv_results_)
df_cv_results_[['param_elastic_net_regression__alpha', 'param_elastic_net_regression__l1_ratio', 'mean_test_score']].sort_values("mean_test_score", ascending = False).head()
```

The model that performs the best out of all the given lambda and alpha values is the model with lambda = 1 and alpha = 0.5.
```{python}
elasticft3_pipeline = Pipeline(
  [("dummify_stdz", ct_elasticft3_dummify_stdz),
  ("interactions", ct_elasticft3_inter),
  ("elastic_net_regression", ElasticNet(alpha = 1, l1_ratio = 0.5))]
)

elasticft3_scores = cross_val_score(elasticft3_pipeline, X=X, y=y, scoring="neg_mean_squared_error", cv=5)

elasticft3_mse = elasticft3_scores.mean()*-1
elasticft3_mse
```

The MSE of this feature set is 119,302.370 dollars squared.

The combination of features that performed the best for the elastic net regression model is the model using the five best numeric variables and their interactions with the one best categorical variable: PutOuts, CRBI, Hits, CRuns, and CHits, Division_W (smallest MSE = 119,302.370).

Overall, the combination of features and model that performed best based on the validation metric of MSE is the ridge regression model with PutOuts, Hits, CRBI, CRuns, and CHits, Division_W as features (smallest MSE = 119,058.886).

# Part III. Discussion

## A. Ridge
**Compare your Ridge models with your ordinary regression models. How did your coefficients compare? Why does this make sense?**
```{python}
lr_ridge_coefdf = lr_coef_df.merge(ridge_coef_df, on = "Variable", suffixes=("_Linear", "_Ridge"))
lr_ridge_coefdf[["Variable", "Coef_Linear","Coef_Ridge"]]
```

The ridge regression coefficients are generally smaller and less spread than the linear regression coefficients. This makes sense because we found our optimal lambda for the ridge regression model to be 100, which imposes quite a large penalty on our loss function. This penalty puts more emphasis on making the beta values of our ridge regression model as small as possible, instead of minimizing the sum of squared error (like in linear regression). Therefore, we would expect these coefficients to be smaller and less spread.

## B. Lasso
**Compare your LASSO model in I with your three LASSO models in II. Did you get the same lambda results? Why does this make sense? Did you get the same MSEs? Why does this make sense?**

- Lasso model I: lambda = 10, MSE = 121,828.141 dollars squared

- Lasso model II, best numeric: lambda = 10, MSE = 142,236.171 dollars squared

- Lasso model II, best 5 numeric: lambda = 10, MSE = 121,601.438 dollars squared

- Lasso model II, best 5 numeric, best categorical, interactions: lambda = 10, MSE = 119,131.849 dollars squared

I did get the same lambda results for each lasso regression model. This makes sense because for each model, we are using the same preprocessing steps, same discrete grid for potential values of lambda, and same 5-fold cross validation procedure. So even though the feature sets are changing, the process and data used to select lambda stays consistent which leads to the same lambda value being chosen as the optimal result across each model. I did not get the same MSEs. In fact, the smallest MSE result came from the lasso regression model with the five best numeric variables, best categorical variable, and their interactions. This makes sense because the other lasso regression models are either underfitting (lasso model II, best numeric) or overfitting (lasso model I, all predictors) our data, so these models will not have the smallest MSE. The next best performing model is lasso model II with the best 5 numeric variables. However, given that Division_W (the best categorical variable) is the second most impactful/important variable in the lasso regression model from part I, it makes sense that this including this variable and its interactions between the 5 best numeric variables would decrease the MSE and result in the best performing model.

## C. Elastic Net

**Best numeric**

- Ridge MSE: 193,417.809 dollars squared

- Lasso MSE: 142,236.171 dollars squared

- Elastic Net MSE: 194,082.789 dollars squared

**Best 5 numeric**

- Ridge MSE: 122,442.744 dollars squared

- Lasso MSE: 121,601.438 dollars squared

- Elastic Net MSE: 122,611.710 dollars squared

**Best 5 numeric, categorical, interactions**

- Ridge MSE: 119,058.886 dollars squared

- Lasso MSE: 119,131.849 dollars squared

- Elastic Net MSE: 119,302.370 dollars squared

Interestingly, my elastic net regression models did not "win" across any of the 3 feature sets. Lasso regression resulted in the smallest MSE for the best single numeric and best 5 numeric feature sets, while ridge regression performed the best for the most complex feature set (best 5 numeric, categorical, interactions). However, it would make sense in theory that elastic net regression performs the best across the feature sets due to this regression technique implementing both the ridge and lasso penalties to our loss function. This allows us to capture the benefits of stabalization of correlated predictors (ridge penalty) and automatic feature selection (lasso penalty). It is possible that my elastic net models did not perform the best because of the discrete parameter grids I explored and/or this data leaning strongly toward a pure ridge or lasso penalty, so the extra alpha term could potentially increase complexity to our loss function for no reason.

# Part IV. Final Model

As mentioned at the end of part II, the combination of features and models that performed best based on the validation metric of MSE is the ridge regression model with PutOuts, Hits, CRBI, CRuns, and CHits, Division_W as predictors (smallest MSE = 119,058.886). 

Let's fit this pipeline on the full dataset:
```{python}
ridgeft3_pipeline_final = Pipeline(
  [("dummify_stdz", ct_ridgeft3_dummify_stdz),
  ("interactions", ct_ridgeft3_inter),
  ("ridge_regression", Ridge(alpha = 100))]
)

ridge_pipeline_final_fitted = ridgeft3_pipeline_final.fit(X, y)
best_model_predicted_y = ridge_pipeline_final_fitted.predict(X)
actual_y = baseball["Salary"]

y_values = {"Predicted Salary": best_model_predicted_y, "Actual Salary": actual_y}
y_values = pd.DataFrame(y_values)

(ggplot(y_values,
aes(
  x = "Actual Salary",
  y = "Predicted Salary"
))
+ geom_point()
+ theme_bw()
+ labs(x = "Actual Salary (1000s $)", y = "Predicted Salary (1000s $)", title = "Predicted vs. Actual Salary")
+ geom_abline(slope=1, intercept=0, linetype="dashed", color = "red")
+ scale_y_continuous(limits = (0, 2600), breaks = [500, 1000, 1500, 2000, 2500], labels = [500, 1000, 1500, 2000, 2500])
+ scale_x_continuous(limits = (0, 2600), breaks = [500, 1000, 1500, 2000, 2500], labels = [500, 1000, 1500, 2000, 2500])
)
```

It seems that even the "best" performing model doesn't necessarily predict our actual baseball salary values perfectly. The plot above shows instances where our model greatly underpredits actual baseball salaries and generally does not closely follow the red dashed line, representing perfect predictions. Overall, this shows me that there is really no "best" or "perfect" model that can predict baseball salary with 100% accuracy. But, this is normal with regression modeling. We explore many different models and choose the one that best predicts our response variable based on some validation metric, not the model that can perfectly predict our response variable.